#ifndef __HEADERS__
#define __HEADERS__
#define _CRT_SECURE_NO_WARNINGS
#include <windows.h>
#include <mmsystem.h>
#include <math.h>
#include <time.h>
#include <iostream>
#include <algorithm>
#include <stdio.h>
#include <vector>
#include <tuple>
#include <stack>
#include <set>
#include <map>
#include <string>
#include <fstream>
#include <algorithm>
#include <irrKlang.h>
#include "AudioManager.h"
#include "Circle.h"
#include "CollisionManager.h"
#include "ColorManager.h"
#include "Object.h"
#include "OpenGL.h"
#include "KeyboardManager.h"
#include "GameManager.h"
#include "PaddleManager.h"
#include "BallsManager.h"
#include "BulletsManager.h"
#include "PowerUpsManager.h"
#include "BricksManager.h"
#include "WallManager.h"
#include "BoardManager.h"
#include "MenuManager.h"
#include "FieldManager.h"
#include "ParticlesManager.h"
#include "MouseManager.h"
#include "LevelManager.h"
#include "DrawManager.h"
#include "WindowManager.h"
#include "TimeManager.h"
#include "TextManager.h"
#include "ScoreManager.h"
#include "ScoreFont.h"
#include "TextureManager.h"
#include "Ball.h"
#define max(a,b) (a>b?a:b)
#define min(a,b) (a<b?a:b)
#define PI (acos(-1.0))
#endif